import fourier_hardware_py
config = fourier_hardware_py.HardwareConfigHelper("/usr/local/config/fourier_hardware/gr2t2")
config.changeControlGroupName("head","head1")
config.changeControlGroupMotorKind("head1","fake")
config.changeControlGroupFilter("head1",False)
config.changeControlGroupMotorMode("head1","pd")
config.changeRobotName("hahaha")
config.changeRobotControlStep(0.0025)
print("size of left manipulator motors", config.getControlGroupMotorSize("left_manipulator"))
config.changeControlGroupMotorPosOffsets("head1",[0.1,0.2])
print(config.getRobotName())
print(config.getControlGroupNames())
print(config.getControlGroupMotorKind("head1"))
print(config.getControlGroupMotorMode("head1"))
config.printHardwareConfig()

hardware = fourier_hardware_py.FourierHardware("/usr/local/config/fourier_hardware/gr2t2",config)
state = hardware.readRealRobotState()
print(state.q)
hardware.enableRobot()
